# Generated by Django 2.1.3 on 2018-11-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_datetime', models.DateTimeField()),
                ('stage', models.CharField(choices=[('FEST', 'Фестиваль'), ('CUP', 'Кубок'), ('8', 'Одна Восьмая'), ('4', 'Одна Четвертая'), ('2', 'Полуфинал'), ('1', 'Финал')], max_length=40)),
                ('description', models.TextField()),
                ('teams', models.ManyToManyField(to='teams.Team')),
            ],
        ),
    ]
