# Generated by Django 2.1.3 on 2018-11-13 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='season',
            field=models.IntegerField(null=True, verbose_name=((2018, '2018'), (2019, '2019'))),
        ),
    ]
