# Generated by Django 2.1.3 on 2018-11-24 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_game_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='game',
            name='season',
            field=models.IntegerField(choices=[(2018, '2018'), (2019, '2019')], null=True),
        ),
    ]
