# Generated by Django 2.1.3 on 2018-11-24 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20181124_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='stage',
            field=models.CharField(choices=[('FEST', 'Фестиваль'), ('CUP', 'Кубок'), ('ONE_EIGHT', 'Одна Восьмая'), ('QUATERFINAL', 'Одна Четвертая'), ('SEMIFINAL', 'Полуфинал'), ('FINAL', 'Финал')], max_length=40),
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('LIVE', 'Live'), ('FINISHED', 'Finished'), ('UPCOMING', 'Upcoming')], default='UPCOMING', max_length=40),
        ),
    ]
