# Generated by Django 2.1.3 on 2018-11-24 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20181124_1403'),
        ('games', '0005_auto_20181124_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='polls',
            field=models.ManyToManyField(to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='game',
            name='teams',
            field=models.ManyToManyField(blank=True, to='teams.Team'),
        ),
    ]
